apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-cloud-order-deployment
spec:
  selector:
    matchLabels:
      app: spring-cloud-order-service
  replicas: 3
  template:
    metadata:
      labels:
        app: spring-cloud-order-service
    spec:
      containers:
        - name: spring-cloud-order-deployment
          image: spring-cloud-order-service:0.0.1
          ports:
            - containerPort: 8088
          env:   # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: spring-cloud-order-svc
spec:
  selector:
    app: spring-cloud-order-service
  ports:
    - protocol: "TCP"
      port: 8088 # The port that the service is running on in the cluster
      targetPort: 8088 # The port exposed by the service
  type: NodePort # type of the service.

