//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.10 at 07:34:52 PM SGT 
//


package com.home.java.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for InwardTransport element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="InwardTransport">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}InArrivalDate"/>
 *           &lt;element ref="{}InLoadingPort"/>
 *           &lt;element ref="{}InMawbObl"/>
 *           &lt;element ref="{}InTransIdentifier"/>
 *           &lt;element ref="{}InAircraftName"/>
 *           &lt;element ref="{}InAircraftId"/>
 *           &lt;element ref="{}InVoyageId"/>
 *           &lt;element ref="{}InEta"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inArrivalDate",
    "inLoadingPort",
    "inMawbObl",
    "inTransIdentifier",
    "inAircraftName",
    "inAircraftId",
    "inVoyageId",
    "inEta"
})
@XmlRootElement(name = "InwardTransport")
public class InwardTransport {

    @XmlElement(name = "InArrivalDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inArrivalDate;
    @XmlElement(name = "InLoadingPort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inLoadingPort;
    @XmlElement(name = "InMawbObl")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inMawbObl;
    @XmlElement(name = "InTransIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inTransIdentifier;
    @XmlElement(name = "InAircraftName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inAircraftName;
    @XmlElement(name = "InAircraftId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inAircraftId;
    @XmlElement(name = "InVoyageId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inVoyageId;
    @XmlElement(name = "InEta")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String inEta;

    /**
     * Gets the value of the inArrivalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInArrivalDate() {
        return inArrivalDate;
    }

    /**
     * Sets the value of the inArrivalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInArrivalDate(String value) {
        this.inArrivalDate = value;
    }

    /**
     * Gets the value of the inLoadingPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInLoadingPort() {
        return inLoadingPort;
    }

    /**
     * Sets the value of the inLoadingPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInLoadingPort(String value) {
        this.inLoadingPort = value;
    }

    /**
     * Gets the value of the inMawbObl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInMawbObl() {
        return inMawbObl;
    }

    /**
     * Sets the value of the inMawbObl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInMawbObl(String value) {
        this.inMawbObl = value;
    }

    /**
     * Gets the value of the inTransIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTransIdentifier() {
        return inTransIdentifier;
    }

    /**
     * Sets the value of the inTransIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTransIdentifier(String value) {
        this.inTransIdentifier = value;
    }

    /**
     * Gets the value of the inAircraftName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInAircraftName() {
        return inAircraftName;
    }

    /**
     * Sets the value of the inAircraftName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInAircraftName(String value) {
        this.inAircraftName = value;
    }

    /**
     * Gets the value of the inAircraftId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInAircraftId() {
        return inAircraftId;
    }

    /**
     * Sets the value of the inAircraftId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInAircraftId(String value) {
        this.inAircraftId = value;
    }

    /**
     * Gets the value of the inVoyageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInVoyageId() {
        return inVoyageId;
    }

    /**
     * Sets the value of the inVoyageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInVoyageId(String value) {
        this.inVoyageId = value;
    }

    /**
     * Gets the value of the inEta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInEta() {
        return inEta;
    }

    /**
     * Sets the value of the inEta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInEta(String value) {
        this.inEta = value;
    }

}
