//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.10 at 07:34:52 PM SGT 
//


package com.home.java.xml;

import java.math.BigDecimal;
import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the primer.po package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InwardTransportMode_QNAME = new QName("", "InwardTransportMode");
    private final static QName _OutLoadingFinalPort_QNAME = new QName("", "OutLoadingFinalPort");
    private final static QName _OutAircraftName_QNAME = new QName("", "OutAircraftName");
    private final static QName _OutNetTonnage_QNAME = new QName("", "OutNetTonnage");
    private final static QName _InLoadingPort_QNAME = new QName("", "InLoadingPort");
    private final static QName _PmtType_QNAME = new QName("", "PmtType");
    private final static QName _TotalOuterPackUnit_QNAME = new QName("", "TotalOuterPackUnit");
    private final static QName _DocumentID_QNAME = new QName("", "DocumentID");
    private final static QName _OutDischargePort_QNAME = new QName("", "OutDischargePort");
    private final static QName _ReleaseCode_QNAME = new QName("", "ReleaseCode");
    private final static QName _InAircraftId_QNAME = new QName("", "InAircraftId");
    private final static QName _OutTowingVesselId_QNAME = new QName("", "OutTowingVesselId");
    private final static QName _OutAircraftId_QNAME = new QName("", "OutAircraftId");
    private final static QName _OutMawbObl_QNAME = new QName("", "OutMawbObl");
    private final static QName _OutLoadingNextPort_QNAME = new QName("", "OutLoadingNextPort");
    private final static QName _DeclRemarks_QNAME = new QName("", "DeclRemarks");
    private final static QName _PackingType_QNAME = new QName("", "PackingType");
    private final static QName _FileName_QNAME = new QName("", "FileName");
    private final static QName _InTransIdentifier_QNAME = new QName("", "InTransIdentifier");
    private final static QName _MsgVersion_QNAME = new QName("", "MsgVersion");
    private final static QName _TotalGrossWeight_QNAME = new QName("", "TotalGrossWeight");
    private final static QName _PrevPermitNumber_QNAME = new QName("", "PrevPermitNumber");
    private final static QName _OutVoyageId_QNAME = new QName("", "OutVoyageId");
    private final static QName _Shipper_QNAME = new QName("", "Shipper");
    private final static QName _OutTowingVesselName_QNAME = new QName("", "OutTowingVesselName");
    private final static QName _OutVesselNationality_QNAME = new QName("", "OutVesselNationality");
    private final static QName _UserID_QNAME = new QName("", "UserID");
    private final static QName _InEta_QNAME = new QName("", "InEta");
    private final static QName _DocumentType_QNAME = new QName("", "DocumentType");
    private final static QName _InMawbObl_QNAME = new QName("", "InMawbObl");
    private final static QName _ForwarderRef_QNAME = new QName("", "ForwarderRef");
    private final static QName _OutTransIdentifier_QNAME = new QName("", "OutTransIdentifier");
    private final static QName _PermitRemarks_QNAME = new QName("", "PermitRemarks");
    private final static QName _Consignee_QNAME = new QName("", "Consignee");
    private final static QName _MsgType_QNAME = new QName("", "MsgType");
    private final static QName _OutDepartureDate_QNAME = new QName("", "OutDepartureDate");
    private final static QName _OutwardTransportMode_QNAME = new QName("", "OutwardTransportMode");
    private final static QName _ShipperRef_QNAME = new QName("", "ShipperRef");
    private final static QName _TotalOuterPack_QNAME = new QName("", "TotalOuterPack");
    private final static QName _InAircraftName_QNAME = new QName("", "InAircraftName");
    private final static QName _OutEtd_QNAME = new QName("", "OutEtd");
    private final static QName _ReceiptCode_QNAME = new QName("", "ReceiptCode");
    private final static QName _OutDestCountry_QNAME = new QName("", "OutDestCountry");
    private final static QName _TotalGrossWeightUnit_QNAME = new QName("", "TotalGrossWeightUnit");
    private final static QName _SubmissionDate_QNAME = new QName("", "SubmissionDate");
    private final static QName _ReceiptName_QNAME = new QName("", "ReceiptName");
    private final static QName _ReleaseName_QNAME = new QName("", "ReleaseName");
    private final static QName _InVoyageId_QNAME = new QName("", "InVoyageId");
    private final static QName _InArrivalDate_QNAME = new QName("", "InArrivalDate");
    private final static QName _OutVesselType_QNAME = new QName("", "OutVesselType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tnets.dms.shipment.factory.PermitData
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link PermitData }
     * 
     */
    public PermitData createPermitData() {
        return new PermitData();
    }

    /**
     * Create an instance of {@link InwardTransport }
     * 
     */
    public InwardTransport createInwardTransport() {
        return new InwardTransport();
    }

    /**
     * Create an instance of {@link OutwardTransport }
     * 
     */
    public OutwardTransport createOutwardTransport() {
        return new OutwardTransport();
    }

    /**
     * Create an instance of {@link SupportDocs }
     * 
     */
    public SupportDocs createSupportDocs() {
        return new SupportDocs();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InwardTransportMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInwardTransportMode(String value) {
        return new JAXBElement<String>(_InwardTransportMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutLoadingFinalPort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutLoadingFinalPort(String value) {
        return new JAXBElement<String>(_OutLoadingFinalPort_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutAircraftName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutAircraftName(String value) {
        return new JAXBElement<String>(_OutAircraftName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutNetTonnage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutNetTonnage(String value) {
        return new JAXBElement<String>(_OutNetTonnage_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InLoadingPort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInLoadingPort(String value) {
        return new JAXBElement<String>(_InLoadingPort_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PmtType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPmtType(String value) {
        return new JAXBElement<String>(_PmtType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalOuterPackUnit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTotalOuterPackUnit(String value) {
        return new JAXBElement<String>(_TotalOuterPackUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocumentID")
    public JAXBElement<BigInteger> createDocumentID(BigInteger value) {
        return new JAXBElement<BigInteger>(_DocumentID_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutDischargePort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutDischargePort(String value) {
        return new JAXBElement<String>(_OutDischargePort_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReleaseCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReleaseCode(String value) {
        return new JAXBElement<String>(_ReleaseCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InAircraftId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInAircraftId(String value) {
        return new JAXBElement<String>(_InAircraftId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutTowingVesselId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutTowingVesselId(String value) {
        return new JAXBElement<String>(_OutTowingVesselId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutAircraftId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutAircraftId(String value) {
        return new JAXBElement<String>(_OutAircraftId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutMawbObl")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutMawbObl(String value) {
        return new JAXBElement<String>(_OutMawbObl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutLoadingNextPort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutLoadingNextPort(String value) {
        return new JAXBElement<String>(_OutLoadingNextPort_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DeclRemarks")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDeclRemarks(String value) {
        return new JAXBElement<String>(_DeclRemarks_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PackingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPackingType(String value) {
        return new JAXBElement<String>(_PackingType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FileName")
    public JAXBElement<String> createFileName(String value) {
        return new JAXBElement<String>(_FileName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InTransIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInTransIdentifier(String value) {
        return new JAXBElement<String>(_InTransIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgVersion")
    public JAXBElement<BigInteger> createMsgVersion(BigInteger value) {
        return new JAXBElement<BigInteger>(_MsgVersion_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalGrossWeight")
    public JAXBElement<BigDecimal> createTotalGrossWeight(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TotalGrossWeight_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PrevPermitNumber")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPrevPermitNumber(String value) {
        return new JAXBElement<String>(_PrevPermitNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutVoyageId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutVoyageId(String value) {
        return new JAXBElement<String>(_OutVoyageId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Shipper")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShipper(String value) {
        return new JAXBElement<String>(_Shipper_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutTowingVesselName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutTowingVesselName(String value) {
        return new JAXBElement<String>(_OutTowingVesselName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutVesselNationality")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutVesselNationality(String value) {
        return new JAXBElement<String>(_OutVesselNationality_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserID")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createUserID(String value) {
        return new JAXBElement<String>(_UserID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InEta")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInEta(String value) {
        return new JAXBElement<String>(_InEta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DocumentType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createDocumentType(String value) {
        return new JAXBElement<String>(_DocumentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InMawbObl")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInMawbObl(String value) {
        return new JAXBElement<String>(_InMawbObl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ForwarderRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createForwarderRef(String value) {
        return new JAXBElement<String>(_ForwarderRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutTransIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutTransIdentifier(String value) {
        return new JAXBElement<String>(_OutTransIdentifier_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PermitRemarks")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createPermitRemarks(String value) {
        return new JAXBElement<String>(_PermitRemarks_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Consignee")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createConsignee(String value) {
        return new JAXBElement<String>(_Consignee_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MsgType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMsgType(String value) {
        return new JAXBElement<String>(_MsgType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutDepartureDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutDepartureDate(String value) {
        return new JAXBElement<String>(_OutDepartureDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutwardTransportMode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutwardTransportMode(String value) {
        return new JAXBElement<String>(_OutwardTransportMode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ShipperRef")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createShipperRef(String value) {
        return new JAXBElement<String>(_ShipperRef_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalOuterPack")
    public JAXBElement<BigInteger> createTotalOuterPack(BigInteger value) {
        return new JAXBElement<BigInteger>(_TotalOuterPack_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InAircraftName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInAircraftName(String value) {
        return new JAXBElement<String>(_InAircraftName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutEtd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutEtd(String value) {
        return new JAXBElement<String>(_OutEtd_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReceiptCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReceiptCode(String value) {
        return new JAXBElement<String>(_ReceiptCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutDestCountry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutDestCountry(String value) {
        return new JAXBElement<String>(_OutDestCountry_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TotalGrossWeightUnit")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createTotalGrossWeightUnit(String value) {
        return new JAXBElement<String>(_TotalGrossWeightUnit_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SubmissionDate")
    public JAXBElement<String> createSubmissionDate(String value) {
        return new JAXBElement<String>(_SubmissionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReceiptName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReceiptName(String value) {
        return new JAXBElement<String>(_ReceiptName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ReleaseName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createReleaseName(String value) {
        return new JAXBElement<String>(_ReleaseName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InVoyageId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInVoyageId(String value) {
        return new JAXBElement<String>(_InVoyageId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "InArrivalDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInArrivalDate(String value) {
        return new JAXBElement<String>(_InArrivalDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "OutVesselType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createOutVesselType(String value) {
        return new JAXBElement<String>(_OutVesselType_QNAME, String.class, null, value);
    }

}
