//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.10 at 07:34:52 PM SGT 
//


package com.home.java.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for OutwardTransport element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="OutwardTransport">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}OutDepartureDate"/>
 *           &lt;element ref="{}OutDischargePort"/>
 *           &lt;element ref="{}OutDestCountry"/>
 *           &lt;element ref="{}OutMawbObl"/>
 *           &lt;element ref="{}OutTransIdentifier"/>
 *           &lt;element ref="{}OutAircraftName"/>
 *           &lt;element ref="{}OutAircraftId"/>
 *           &lt;element ref="{}OutVoyageId"/>
 *           &lt;element ref="{}OutEtd"/>
 *           &lt;element ref="{}OutLoadingNextPort"/>
 *           &lt;element ref="{}OutLoadingFinalPort"/>
 *           &lt;element ref="{}OutVesselType"/>
 *           &lt;element ref="{}OutNetTonnage"/>
 *           &lt;element ref="{}OutVesselNationality"/>
 *           &lt;element ref="{}OutTowingVesselName"/>
 *           &lt;element ref="{}OutTowingVesselId"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outDepartureDate",
    "outDischargePort",
    "outDestCountry",
    "outMawbObl",
    "outTransIdentifier",
    "outAircraftName",
    "outAircraftId",
    "outVoyageId",
    "outEtd",
    "outLoadingNextPort",
    "outLoadingFinalPort",
    "outVesselType",
    "outNetTonnage",
    "outVesselNationality",
    "outTowingVesselName",
    "outTowingVesselId"
})
@XmlRootElement(name = "OutwardTransport")
public class OutwardTransport {

    @XmlElement(name = "OutDepartureDate")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outDepartureDate;
    @XmlElement(name = "OutDischargePort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outDischargePort;
    @XmlElement(name = "OutDestCountry")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outDestCountry;
    @XmlElement(name = "OutMawbObl")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outMawbObl;
    @XmlElement(name = "OutTransIdentifier")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outTransIdentifier;
    @XmlElement(name = "OutAircraftName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outAircraftName;
    @XmlElement(name = "OutAircraftId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outAircraftId;
    @XmlElement(name = "OutVoyageId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outVoyageId;
    @XmlElement(name = "OutEtd")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outEtd;
    @XmlElement(name = "OutLoadingNextPort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outLoadingNextPort;
    @XmlElement(name = "OutLoadingFinalPort")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outLoadingFinalPort;
    @XmlElement(name = "OutVesselType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outVesselType;
    @XmlElement(name = "OutNetTonnage")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outNetTonnage;
    @XmlElement(name = "OutVesselNationality")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outVesselNationality;
    @XmlElement(name = "OutTowingVesselName")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outTowingVesselName;
    @XmlElement(name = "OutTowingVesselId")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String outTowingVesselId;

    /**
     * Gets the value of the outDepartureDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutDepartureDate() {
        return outDepartureDate;
    }

    /**
     * Sets the value of the outDepartureDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutDepartureDate(String value) {
        this.outDepartureDate = value;
    }

    /**
     * Gets the value of the outDischargePort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutDischargePort() {
        return outDischargePort;
    }

    /**
     * Sets the value of the outDischargePort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutDischargePort(String value) {
        this.outDischargePort = value;
    }

    /**
     * Gets the value of the outDestCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutDestCountry() {
        return outDestCountry;
    }

    /**
     * Sets the value of the outDestCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutDestCountry(String value) {
        this.outDestCountry = value;
    }

    /**
     * Gets the value of the outMawbObl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutMawbObl() {
        return outMawbObl;
    }

    /**
     * Sets the value of the outMawbObl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutMawbObl(String value) {
        this.outMawbObl = value;
    }

    /**
     * Gets the value of the outTransIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutTransIdentifier() {
        return outTransIdentifier;
    }

    /**
     * Sets the value of the outTransIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutTransIdentifier(String value) {
        this.outTransIdentifier = value;
    }

    /**
     * Gets the value of the outAircraftName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutAircraftName() {
        return outAircraftName;
    }

    /**
     * Sets the value of the outAircraftName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutAircraftName(String value) {
        this.outAircraftName = value;
    }

    /**
     * Gets the value of the outAircraftId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutAircraftId() {
        return outAircraftId;
    }

    /**
     * Sets the value of the outAircraftId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutAircraftId(String value) {
        this.outAircraftId = value;
    }

    /**
     * Gets the value of the outVoyageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutVoyageId() {
        return outVoyageId;
    }

    /**
     * Sets the value of the outVoyageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutVoyageId(String value) {
        this.outVoyageId = value;
    }

    /**
     * Gets the value of the outEtd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutEtd() {
        return outEtd;
    }

    /**
     * Sets the value of the outEtd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutEtd(String value) {
        this.outEtd = value;
    }

    /**
     * Gets the value of the outLoadingNextPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutLoadingNextPort() {
        return outLoadingNextPort;
    }

    /**
     * Sets the value of the outLoadingNextPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutLoadingNextPort(String value) {
        this.outLoadingNextPort = value;
    }

    /**
     * Gets the value of the outLoadingFinalPort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutLoadingFinalPort() {
        return outLoadingFinalPort;
    }

    /**
     * Sets the value of the outLoadingFinalPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutLoadingFinalPort(String value) {
        this.outLoadingFinalPort = value;
    }

    /**
     * Gets the value of the outVesselType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutVesselType() {
        return outVesselType;
    }

    /**
     * Sets the value of the outVesselType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutVesselType(String value) {
        this.outVesselType = value;
    }

    /**
     * Gets the value of the outNetTonnage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutNetTonnage() {
        return outNetTonnage;
    }

    /**
     * Sets the value of the outNetTonnage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutNetTonnage(String value) {
        this.outNetTonnage = value;
    }

    /**
     * Gets the value of the outVesselNationality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutVesselNationality() {
        return outVesselNationality;
    }

    /**
     * Sets the value of the outVesselNationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutVesselNationality(String value) {
        this.outVesselNationality = value;
    }

    /**
     * Gets the value of the outTowingVesselName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutTowingVesselName() {
        return outTowingVesselName;
    }

    /**
     * Sets the value of the outTowingVesselName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutTowingVesselName(String value) {
        this.outTowingVesselName = value;
    }

    /**
     * Gets the value of the outTowingVesselId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutTowingVesselId() {
        return outTowingVesselId;
    }

    /**
     * Sets the value of the outTowingVesselId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutTowingVesselId(String value) {
        this.outTowingVesselId = value;
    }

}
