//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.10 at 07:34:52 PM SGT 
//


package com.home.java.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PermitData element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="PermitData">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{}Header"/>
 *           &lt;element ref="{}InwardTransport"/>
 *           &lt;element ref="{}OutwardTransport"/>
 *           &lt;element ref="{}SupportDocs" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "header",
    "inwardTransport",
    "outwardTransport",
    "supportDocs"
})
@XmlRootElement(name = "PermitData")
public class PermitData {

    @XmlElement(name = "Header")
    protected Header header;
    @XmlElement(name = "InwardTransport")
    protected InwardTransport inwardTransport;
    @XmlElement(name = "OutwardTransport")
    protected OutwardTransport outwardTransport;
    @XmlElement(name = "SupportDocs")
    protected SupportDocs supportDocs;

    /**
     * Gets the value of the header property.
     * 
     * @return
     *     possible object is
     *     {@link Header }
     *     
     */
    public Header getHeader() {
        return header;
    }

    /**
     * Sets the value of the header property.
     * 
     * @param value
     *     allowed object is
     *     {@link Header }
     *     
     */
    public void setHeader(Header value) {
        this.header = value;
    }

    /**
     * Gets the value of the inwardTransport property.
     * 
     * @return
     *     possible object is
     *     {@link InwardTransport }
     *     
     */
    public InwardTransport getInwardTransport() {
        return inwardTransport;
    }

    /**
     * Sets the value of the inwardTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link InwardTransport }
     *     
     */
    public void setInwardTransport(InwardTransport value) {
        this.inwardTransport = value;
    }

    /**
     * Gets the value of the outwardTransport property.
     * 
     * @return
     *     possible object is
     *     {@link OutwardTransport }
     *     
     */
    public OutwardTransport getOutwardTransport() {
        return outwardTransport;
    }

    /**
     * Sets the value of the outwardTransport property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutwardTransport }
     *     
     */
    public void setOutwardTransport(OutwardTransport value) {
        this.outwardTransport = value;
    }

    /**
     * Gets the value of the supportDocs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportDocs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportDocs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportDocs }
     * 
     * 
     */
    public SupportDocs getSupportDocs() {
        if (supportDocs == null) {
            supportDocs = new SupportDocs();
        }
        return this.supportDocs;
    }

	public void setSupportDocs(SupportDocs supportDocs) {
		this.supportDocs = supportDocs;
	}

}
