spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/sabir_home_db
    username: postgres
    password: admin
  flyway:
    url: jdbc:postgresql://localhost:5432/sabir_home_db
    user: postgres
    password: admin