server:
  port: 8761

spring:
  application:
    name: service-registry
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"

#For Logging
logging:
  file:
    name: service-registry.log
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG