#spring:
#  application:
#    name: CUSTOMER-SERVICE
#  config:
#    import: "optional:configserver:http://localhost:8050" #Config Server location
#  mvc:
 #   pathmatch:
 #     matching-strategy: ANT_PATH_MATCHER

