#To Specify Service Running port
server:
  address: 0.0.0.0
  port: 8087

#To Register with Service Registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#for zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  
#For Logging
logging:
  file:
    name: customer-service.log
  level:
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG