#To Specify Service Running port 
server:
  address: 0.0.0.0
  port: 8083

    
#To Register with Service Registry
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#For Zipkin
management:
  tracing:
    sampling:
      probability: 1.0
  
#For Logging
logging:
  file:
    name: product-service.log
  level:
    io.micrometer.tracing: DEBUG
    com:
      netflix:
        eureka: DEBUG
        discovery: DEBUG

